name: Docs
on:
  push:
    branches:
      - main
  pull_request: {}

env:
  MISE_EXPERIMENTAL: "1"
  MISE_GITHUB_TOKEN: ${{ secrets.GLOSSIA_GITHUB_TOKEN }}
  MISE_SOPS_AGE_KEY: ${{ secrets.MISE_SOPS_AGE_KEY }}
  PNPM_HOME: ~/.pnpm

jobs:
  build:
    name: Build
    runs-on: debian-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm/store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - uses: https://github.com/jdx/mise-action@v2
        with:
          cache: true
      - run: mise run build
